title: 学习python🐍
description: Study Python|
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

blog_button:
  title: Blog
  description: Visit blog
